### ISSUE TITLE
Information of timestamp

### ISSUE THREAD

**Issue by eugenelyj** [PIX2NVS/NVS2Graph#4]
Hi! Thanks for sharing the code! I notice that timestamp of events are not stored aftre data-preprocessing(while spatial positions are stored as 'pseudo' and polarity are stored as 'feature'). Do experiments show that timestamps are not so important or there is any other reason?

**Comment by eugenelyj** [comment]
As for doing non-uniform sampling in data-preprocessing part, could you give some hints? For example, do you use some methods in pcl library or some other library?  I am looking forward to your reply :)

**Comment by PIX2NVS** [comment]
Hi, thanks for your interests. 

1. Yes, we only take the x, y addresses as pseudo positions of nodes. Object classification (our task) is much more like appreance recognition, where the spatial information is much more important so that we ignore the timestamps that provide the temporal information. We did not confirm this assumption by any experiments, so you can explore it on your side to see whether you can obtain higher accuracy by including timestamps.

 2. In terms of non-uniform sampling, as described in the text, one event is randomly selected from a space-time volume with the maximum number of events inside. If we consider s{ei} to be such a grid containing k events, then only one event ei (i ∈ [1, k]) is randomly sampled in this space-time volume. It is not difficult to implement it in your own code. If you wanna refer to libraries, you can consider VoxelGrid filter in PCL  or pcdownsample function in Matlab. I do not think methods of sampling could affect the results drastically.  Just leverage one to decrease the storage and computational cost so that your GPU memory can consume. 

Let me know if any more questions.

**Comment by eugenelyj** [comment]
Thank you so much! It helps a lot.
